version: "3.9"

services:

  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./inital.sql:/docker-entrypoint-initdb.d/inital.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
