version: '3'
services:
    nginx:
      container_name: nginx
      image: nginx
      ports:
        - "80:80"
        - "10815:10815"
        - "10814:10814"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      restart: always