version: "3.9"
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - PHP_UPLOAD_MAX_FILESIZE=100MB