version: "3.9"
services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
      - './initial.sql:/docker-entrypoint-initdb.d/initial.sql'

  # phpadmin
  adminer:
    image: adminer:4.8.1
    ports:
      - "8081:8080"