version: "3.9"

services:
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: >
      --requirepass 123456
    volumes:
      - ./data:/data
    restart: always
    networks:
      - redis_net

  redis_comndr:
    depends_on:
      - redis
    image: rediscommander/redis-commander
    ports:
      - 8082:8081
    links:
      - redis:redis
    environment:
      - REDIS_HOSTS=local:redis:6379:0:123456
    restart: always
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge