version: "3.9"

services:
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      # - REDIS_PASSWORD=123456
    volumes:
      - ./data:/data
    restart: always
    networks:
      - redis_net

  redis_comndr:
    depends_on:
      - redis
    image: tenstartups/redis-commander
    command: --redis-host redis
    ports:
      - 8082:8081
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge